package Day20;

import java.util.Scanner;

class A 
{
	
}
public class ExceptionExample {
	public static void main(String[] args) throws DevidedByZeroException, ArithmeticException{
		Scanner sc = new Scanner(System.in);

		int a = 10;
		int b = sc.nextInt();
		try {
			if (b == 0) {
				throw new DevidedByZeroException();
			}
			System.out.println(a / b);
		} catch (ArithmeticException e) {

			System.out.println("devide by zeo");
		} catch (DevidedByZeroException e) {
			System.out.println("user defined exception handled");
		} finally {
			System.out.println("end");
			sc.close();
		}

	}

}

